name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master/done
    - name: make check
      run: make check
    - name: make style
      run: make style
    - name: make clean
      run: make clean
